create table if not exists users (
  id integer generated by default as identity primary key,
  email text not null unique,
  username text not null unique,
  nickname text not null unique,
  password text not null,
  department text not null,
  student_year integer not null,
  bio text not null default '',
  manner_score numeric(4, 1) not null default 36.5,
  profile_image_url text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists posts (
  id integer generated by default as identity primary key,
  post_name text not null unique,
  author_id integer not null references users(id) on delete cascade,
  title text not null,
  content text not null,
  category text not null,
  subcategory text not null,
  price integer,
  status text not null,
  trade_type text,
  location text,
  is_price_offer_allowed boolean not null default false,
  recruitment_target integer,
  recruitment_current integer,
  tags jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists post_images (
  id integer generated by default as identity primary key,
  post_id integer not null references posts(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0
);

create table if not exists post_likes (
  id integer generated by default as identity primary key,
  post_id integer not null references posts(id) on delete cascade,
  user_id integer not null references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

create table if not exists comments (
  id integer generated by default as identity primary key,
  post_id integer not null references posts(id) on delete cascade,
  user_id integer not null references users(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists notifications (
  id integer generated by default as identity primary key,
  recipient_id integer not null references users(id) on delete cascade,
  actor_id integer not null references users(id) on delete cascade,
  post_id integer not null references posts(id) on delete cascade,
  type text not null,
  message text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists chat_rooms (
  id integer generated by default as identity primary key,
  post_id integer not null references posts(id) on delete cascade,
  seller_id integer not null references users(id) on delete cascade,
  buyer_id integer not null references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, seller_id, buyer_id)
);

create table if not exists messages (
  id integer generated by default as identity primary key,
  room_id integer not null references chat_rooms(id) on delete cascade,
  sender_id integer not null references users(id) on delete cascade,
  client_id text,
  content text not null default '',
  image_url text,
  read_by integer[] not null default array[]::integer[],
  created_at timestamptz not null default now()
);

create table if not exists sessions (
  token text primary key,
  user_id integer not null references users(id) on delete cascade,
  persisted boolean not null default false,
  expires_at timestamptz not null
);

create table if not exists verification_codes (
  email text primary key,
  code text not null,
  verified boolean not null default false,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists posts_created_at_idx on posts(created_at desc);
create index if not exists posts_category_idx on posts(category);
create index if not exists post_images_post_id_idx on post_images(post_id, sort_order);
create index if not exists comments_post_id_idx on comments(post_id, created_at);
create index if not exists notifications_recipient_id_idx on notifications(recipient_id, created_at desc);
create index if not exists chat_rooms_participants_idx on chat_rooms(seller_id, buyer_id);
create index if not exists messages_room_id_idx on messages(room_id, id);
